### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by Anobium** [johnnydrazzi/USB-Stack#1]
Great project.

Johnny trying to rebuild.

Using Microchip Technology PIC PRO Macro Assembler V1.45 build Cx8.   What did you use?

Not getting a HEX that fits in the 0x1000 for the 16f1454.   

I am trying to build the MSD that fits in less than 0x7DB - Do you think this is possible? What could be removed to get it in 0x7DB?

Thank you so much.

**Comment by johnnydrazzi** [comment]
Hi Anobium, I also used XC8 V1.45 Pro. Double check I didn't leave a code offset in the project settings for the MSD example. I tested these examples using a USB bootloader. Also double check when you compile that PRO optimisation is actually being used. Not at a computer right now to check it sorry.

**Comment by johnnydrazzi** [comment]
Hi Anobium, I also used XC8 V1.45 Pro. Double check I didn't leave a code offset in the project settings for the MSD example. I tested these examples using a USB bootloader. Also double check in the output when you compile that PRO optimisation is actually being used. Check optimise for space. Not at a computer right now to check it sorry.

**Comment by Anobium** [comment]
Very grateful.  Still no progress here.

I am compiling to create this file as follows.  MSD_Examples/MSD_Internal_Example/PIC16F145X.X  I am assuming MSD_examples is correct the code.  Is this correct? 
:  ..USB-Stack-master/USB-Stack-master/USB_Stack_Examples/MSD_Examples/MSD_Internal_Example/PIC16F145X.X/dist/PIC16F1454_PRO/production/PIC16F145X.X.production.hex...

I have loaded the HEX into PK2 GUI.  The code is still exceeds 0x1000 as cab be seen in the picture.

![Annotation 2020-05-24 083701](https://user-images.githubusercontent.com/17933379/82748486-1d47f180-9d9a-11ea-9978-cd1f1c6551e8.png)

If I compare to your HEX....which is correct.

![Annotation 2020-05-24 084317](https://user-images.githubusercontent.com/17933379/82748551-ae1ecd00-9d9a-11ea-8f2a-7d8d6694460b.png)

What school boy error am I making?

**Comment by johnnydrazzi** [comment]
Hmm, not sure what's doing that. I'd check to make sure your version of XC8 is fully licensed (Pro). That's the most likely cause. Even if you select pro, it may still not be optimised. The output window should tell you after a compilation. The code for PIC16F145X only works on the pro version. The memory is very tight on this chip. In XC8 Global Options->XC8 Linker->Rom Ranges make sure "0-7FF,800-FFF" is there. If your code can't fit in the Rom Ranges it should have an error on compilation. Did an error occur?

Also leave FLASH_SPACE_START = 0x01000 and END_OF_FLASH = 0x02000 in main.c.

**Comment by johnnydrazzi** [comment]
Hmm, not sure what's doing that. I'd check to make sure your version of XC8 is fully licensed (Pro), that's the most likely cause. Even if you select pro, it may still not be optimised. The output window should tell you after a compilation. This MSD Internal example for PIC16F145X only works on the pro licensed version of XC8, the memory is very tight on this chip. In XC8 Global Options->XC8 Linker->Rom Ranges make sure "0-7FF,800-FFF" is there. If your code can't fit in the Rom Ranges it should have an error on compilation. Did an error occur?

Also leave FLASH_SPACE_START = 0x01000 and END_OF_FLASH = 0x02000 in main.c.

**Comment by Anobium** [comment]
Cheers.  No progress,

Checked a main():
![image](https://user-images.githubusercontent.com/17933379/82792106-c0663d00-9e66-11ea-96ab-5eb3e0ea0931.png)

Checked Rom ranges:
![image](https://user-images.githubusercontent.com/17933379/82791978-90b73500-9e66-11ea-87c5-5de0572e6e8e.png)

Checked Pro mode:
See [outoput.txt](https://github.com/johnnydrazzi/USB-Stack/files/4676087/outoput.txt).

Check optimisation changes in 1.45 Release note:
No change,

Most odd... what is different?

**Comment by johnnydrazzi** [comment]
Very strange. Is this a clean copy of the example or modified? If modified, send me a copy of your project and I'll try work it out.

Since you messaged me I've been in the process of updating this library. I have a version here that support's the latest compiler v2.2.0 and C99. Let me know if that would be helpful.

John.

**Comment by Anobium** [comment]
Best if I share the goal - it will help.

I develop Great Cow BASIC. An Open Source compiler for PIC and AVR.   We have users in, truly, Africa who use Great Cow BASIC for education.  The challenge is providing a solution that is very, very low cost.

So, Great Cow BASIC cannot address beyond 0x1000.  This is a hard coded limitation. Never really thought the Bootload would not sit outside the first page. 

This may explain why the ask for 16F1454 that has less functionality, and, looking for a bootloader is about 0x800.

So, if you think that 0x800 is just not achievable then I should give up and not waste anymore of you time.

Your thoughts on the challenge?

**Comment by johnnydrazzi** [comment]
Sorry I'm a little lost. So you're wanting to make a bootloader using MSD Internal Example as a starting point? Is it the unchanged example that won't compile lower than 0x1000 or your application/bootloader? Why the limitation of 0x800? Your saying because your compiler can't address beyond 0x1000?  If I understand right, you want 0x000 to 0x800 your bootloader, 0x800 to 0x1000 is user space and 0x1000 to 0x2000 is unusable space due to Cow BASIC limitation? I don't think my USB uC/USB stack can fit in 0x800 words. It was difficult fitting it into 0x1000. I'll have a look tomorrow and see if USB uC bootloader for 16F145X can be made smaller.

**Comment by Anobium** [comment]
Sorry to confuse.

The posts with the reports are the stock downloaded not changed.  So, that an issue here - It may not be be at your end.

The Great Cow BASIC constraints. Great Cow BASIC page handler assumes that page 0 is available.  When Hugh wrote the compiler (11 years ago, he was 13!!) that was his assumption.  So,  0x800 is workable within Great Cow BASIC but I understand this may be difficult.

Thank you for looking.

**Comment by johnnydrazzi** [comment]
Hey, I've uploaded the source code for the 145X bootloader on my USB uC repository... I tried to get the code size as small as possible but only achieved down to 3,935 (0xF5F) words used, 161 (0xA1) free. I have my doubts this bootloader could ever fit in less than one page 0x800, especially written in C... I have seen others write really small USB bootloaders in assembly, CDC, HID and DFU in 512 words or less. Quick google search and you'll find them.

Sorry I couldn't be more help.

John.

**Comment by Anobium** [comment]
John, 

 

Thank you so much for trying.  Truly grateful.  I owe you – want a free license to PICKitPlus as a trade for your time?

 

Option are give up or rewrite a major part of Great Cow BASIC.

 

Again, thank you.

 

Evan

 

 

 

 

 

To solve your Microchip PIC programming problems – use PICKitPlus for the PICKit2 and PICKt3 programmers.  See  <http://www.pickitplus.co.uk> www.pickitplus.co.uk

 

Brain logo with white stroke 100x100

 

Anobium Business Services Limited - Registered Office: Anobium House, Bramley, Surrey, UK GU5 0DP- Registered in England No: 12232398. 



Anobium Business Services Limited -- This message is transmitted to you by or on behalf of Anobium Business Services Limited. It is intended exclusively for the addressee. The substance of this message, along with any attachments, may contain proprietary, confidential or privileged information or information that is otherwise legally exempt from disclosure. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient of this message, you are not authorized to read, print, retain, copy or disseminate any part of this message. If you have received this message in error, please destroy and delete all copies and notify the sender by return e-mail. Regardless of content, this e-mail shall not operate to bind Anobium Business Services Limited to any order or other contract unless pursuant to explicit written agreement or written initiative expressly permitting the use of e-mail for such purpose.
